### ISSUE TITLE
refined error handling

### ISSUE THREAD

**Issue by ghostbuster91** [niqdev/caliban-extras#26]
Hi, 

First of all, thanks for this library, it really makes life easier :) 

Currently I'm implementing error handling in my graphQL app. I defined my own exception to handle all the domain errors which might occur during the resolver's execution. All other errors I wanted to label as unexpected. 

To my surprise errors from the refined library are thrown as `ExecutionException` (I would expect them to be thrown as `ParsingError` but maybe `ParsingErrors` are reserved for internal graphQL parser, I don't know). 

Anyway I would like to return all refined errors as `InvalidInput` or something like that. However currently I don't see how could I differentiate them from other unknown/unexpected `ExecutionException`s.

Any idea on how to tackle that problem?

**Comment by niqdev** [comment]
Hello, thanks! Well... this is really nothing compared to caliban itself! 😅 

If I understand correctly you want to map an error using something like a `leftMap`, which I don't think it is strictly related to this lib... in any case I would recommend to join the zio discord server / caliban channel and ask the question there with an example. They are all very friendly and I'm sure they can give you the right answer there!

I hope this help... just for reference, feel free to post an update here once you solve it and close the pr afterwards.
Thanks

**Comment by ghostbuster91** [comment]
I don't think that we are on the same page.

I know how to map errors, e.g. in my project I have:
```
  def apply(interpreter: GraphQLInterpreter[Any, CalibanError]): GraphQLInterpreter[Any, CalibanError] = {
    interpreter.mapError {
      case e @ CalibanError.ParsingError(msg, _, _, _) =>
        logger.warn(msg, e)
        e.copy(extensions = Some(errorsObj(errorObj(ParsingFail))))
      case e @ CalibanError.ValidationError(msg, _, _, _) =>
        logger.warn(msg, e)
        e.copy(extensions = Some(errorsObj(errorObj(InvalidFail))))
      case e @ CalibanError.ExecutionError(msg, _, _, Some(cause: Fail), _) =>
        logger.error(msg, e)
        e.copy(extensions = Some(errorsObj(cause.failDetails.map(errorObj).toList: _*)))
      case e @ CalibanError.ExecutionError(_, _, _, Some(cause), _) =>
        logger.error(cause.getMessage, e)
        e.copy(msg = cause.getMessage)
      case e @ CalibanError.ExecutionError(msg, _, _, None, _) =>
        logger.error(msg, e)
        e
    }
  }
```

My problem is that errors from caliban-refined integration are being thrown as `ExecutionException` with only a message inside (without the cause), so there is no way to distinguish it from other errors apart from relaying on strings comparison. Obviously I don't want to relay on strings.

In my opinion it would be helpful if caliban-refined integration would wrap error message with its own error type before wrapping it with `ExecutionException`. I also think that it might be better to throw `ParsingError` instead of `ExecutionError`.

**Comment by niqdev** [comment]
Sorry, I got what you mean now 😓 

I saw #28 and it looks way cleaner, thanks!
Before merge it, regarding the error type, are you still suggesting to change it also after your changes? To be honest, all the argBuilders I've seen so far are returning `ExecutionError`, but I'm very hope to suggestions of course.

```scala
/**
 * Describes an error that happened while parsing a query.
 */
case class ParsingError(...)

/**
 * Describes an error that happened while executing a query.
 */
case class ExecutionError(...)
```

**Comment by ghostbuster91** [comment]
No problem :) 

Glad you like it.

In my opinion `ParsingError` suits better and I wonder why this `ExecutionError` is so popular. Maybe it was easier to use it, I don't know.  Or maybe one person used it and the rest copied :) 

Anyway, if you choose to stick with `ExecutionError` I would suggest wrapping the error with a new throwable class so it can be distinguished from other `ExecutionError`. On the other hand if we use  `ParsingError` there is no need for such wrapping as (at least in my case) all parsing errors are handled in the same way (And I think that it is usually that case).

**Comment by niqdev** [comment]
Ok, honestly I'm not too opinionated on this, but I kinda agree with what you are saying, even though I think it relates more to `happened while`, rather than how.

So, if you are happy I would start merging your pr and release `0.1.5` since it's not a breaking change. If you prefer to change the error type I would suggest, if you have time, to open another pr so that we can talk about it there.

wdyt?

**Comment by ghostbuster91** [comment]
Sure, that's fine by me :)

**Comment by niqdev** [comment]
travis is not in a good mood today 😔 ... i've restarted those jobs several times but they are stuck in the queue forever... i'll close the pr as soon as the new version is released

**Comment by niqdev** [comment]
Version `0.1.5` has been released, thanks for your contribution!
